export const ADD_PATIENT = 'ADD_PATIENT';
export const FETCH_PATIENT_REQUEST = 'FETCH_PATIENT_REQUEST';
export const FETCH_PATIENT_SUCCESS = 'FETCH_PATIENT_SUCCESS';
export const FETCH_PATIENT_FAILED = 'FETCH_PATIENT_FAILED';